version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - /var/jenkins_home   # adding to intract with docker
      - /var/run/docker.sock:/var/run/docker.sock  # adding to intract with docker
      - ./html:/usr/local/apache2/htdocs/

